source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target "RestClient" do
    pod 'Alamofire', '~> 3.2.1'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'SQLite.swift', :git => 'https://github.com/stephencelis/SQLite.swift.git'
    pod 'SWRevealViewController', :git => 'https://github.com/John-Lluch/SWRevealViewController.git'
    pod 'FontAwesome.swift'
    pod 'SwiftLog', :git => "https://github.com/daltoniam/SwiftLog.git"
end